# .slather.yml

coverage_service: html
xcodeproj: ./Alfie/Alfie.xcodeproj
scheme: Alfie
source_directory: ./Alfie
output_directory: ./coverage_report
binary_basename: Alfie
ignore:
  - '../Library/Developer/Xcode/DerivedData/*'
  - '**/DerivedData/*' 
  - '**/L10n*.swift'
  - '**/Mock*.swift'
