// AUTO-GENERATED by Tools/DesignTokenGen — DO NOT EDIT.
// Source: design tokens in SharedUI/DesignTokens. Regenerate: ./Alfie/scripts/generate-design-tokens.sh
// swiftlint:disable all
import SwiftUI

public enum Primitives {
    public enum Border {
        public static let borderStyleSolid: String = "solid"
        public static let borderWeightDefault: CGFloat = CGFloat(1.0)
    }
    public enum Colours {
        public static let neutrals0 = Color(.sRGB, red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0)
        public static let neutrals100 = Color(.sRGB, red: 0.97, green: 0.97, blue: 0.97, opacity: 1.0)
        public static let neutrals200 = Color(.sRGB, red: 0.913725, green: 0.913725, blue: 0.913725, opacity: 1.0)
        public static let neutrals300 = Color(.sRGB, red: 0.803922, green: 0.803922, blue: 0.803922, opacity: 1.0)
        public static let neutrals400 = Color(.sRGB, red: 0.63, green: 0.63, blue: 0.63, opacity: 1.0)
        public static let neutrals500 = Color(.sRGB, red: 0.462745, green: 0.462745, blue: 0.462745, opacity: 1.0)
        public static let neutrals600 = Color(.sRGB, red: 0.290196, green: 0.290196, blue: 0.290196, opacity: 1.0)
        public static let neutrals700 = Color(.sRGB, red: 0.168627, green: 0.168627, blue: 0.168627, opacity: 1.0)
        public static let neutrals800 = Color(.sRGB, red: 0.066667, green: 0.066667, blue: 0.066667, opacity: 1.0)
        public static let neutrals900 = Color(.sRGB, red: 0.023529, green: 0.031373, blue: 0.039216, opacity: 1.0)
        public static let semanticError100 = Color(.sRGB, red: 0.996078, green: 0.94902, blue: 0.945098, opacity: 1.0)
        public static let semanticError200 = Color(.sRGB, red: 0.976471, green: 0.870588, blue: 0.862745, opacity: 1.0)
        public static let semanticError300 = Color(.sRGB, red: 0.917647, green: 0.607843, blue: 0.619608, opacity: 1.0)
        public static let semanticError400 = Color(.sRGB, red: 0.92, green: 0.4048, blue: 0.425686, opacity: 1.0)
        public static let semanticError500 = Color(.sRGB, red: 0.878431, green: 0.243137, blue: 0.25098, opacity: 1.0)
        public static let semanticError600 = Color(.sRGB, red: 0.698698, green: 0.146893, blue: 0.146893, opacity: 1.0)
        public static let semanticError700 = Color(.sRGB, red: 0.583789, green: 0.144047, blue: 0.144047, opacity: 1.0)
        public static let semanticError800 = Color(.sRGB, red: 0.468506, green: 0.021527, blue: 3.8e-05, opacity: 1.0)
        public static let semanticSuccess100 = Color(.sRGB, red: 0.929412, green: 0.968627, blue: 0.905882, opacity: 1.0)
        public static let semanticSuccess200 = Color(.sRGB, red: 0.831373, green: 0.917647, blue: 0.764706, opacity: 1.0)
        public static let semanticSuccess300 = Color(.sRGB, red: 0.640604, green: 0.81, blue: 0.5103, opacity: 1.0)
        public static let semanticSuccess400 = Color(.sRGB, red: 0.517647, green: 0.772549, blue: 0.32549, opacity: 1.0)
        public static let semanticSuccess500 = Color(.sRGB, red: 0.375143, green: 0.65, blue: 0.167143, opacity: 1.0)
        public static let semanticSuccess600 = Color(.sRGB, red: 0.283113, green: 0.57, blue: 0.120795, opacity: 1.0)
        public static let semanticSuccess700 = Color(.sRGB, red: 0.211765, green: 0.513726, blue: 0.086275, opacity: 1.0)
        public static let semanticSuccess800 = Color(.sRGB, red: 0.0, green: 0.384314, blue: 0.003922, opacity: 1.0)
        public static let transparentTransparent = Color(.sRGB, red: 1.0, green: 1.0, blue: 1.0, opacity: 0.0)
    }
    public enum Spacing {
        public static let spacing0: CGFloat = CGFloat(0.0)
        public static let spacing12: CGFloat = CGFloat(12.0)
        public static let spacing124: CGFloat = CGFloat(124.0)
        public static let spacing14: CGFloat = CGFloat(14.0)
        public static let spacing16: CGFloat = CGFloat(16.0)
        public static let spacing18: CGFloat = CGFloat(18.0)
        public static let spacing2: CGFloat = CGFloat(2.0)
        public static let spacing20: CGFloat = CGFloat(20.0)
        public static let spacing220: CGFloat = CGFloat(220.0)
        public static let spacing24: CGFloat = CGFloat(24.0)
        public static let spacing28: CGFloat = CGFloat(28.0)
        public static let spacing32: CGFloat = CGFloat(32.0)
        public static let spacing4: CGFloat = CGFloat(4.0)
        public static let spacing40: CGFloat = CGFloat(40.0)
        public static let spacing48: CGFloat = CGFloat(48.0)
        public static let spacing56: CGFloat = CGFloat(56.0)
        public static let spacing64: CGFloat = CGFloat(64.0)
        public static let spacing8: CGFloat = CGFloat(8.0)
        public static let spacing80: CGFloat = CGFloat(80.0)
        public static let spacing96: CGFloat = CGFloat(96.0)
    }
    public enum Typography {
        public static let fontFamilyBrand: String = "Libre Baskerville"
        public static let fontFamilyPrimaryAndroid: String = "Roboto"
        public static let fontFamilyPrimaryIos: String = "SF Pro"
        public static let fontFamilyPrimaryWeb: String = "Inter"
        public static let fontSizeFontSize12 = Primitives.Spacing.spacing12
        public static let fontSizeFontSize14 = Primitives.Spacing.spacing14
        public static let fontSizeFontSize16 = Primitives.Spacing.spacing16
        public static let fontSizeFontSize18 = Primitives.Spacing.spacing18
        public static let fontSizeFontSize20 = Primitives.Spacing.spacing20
        public static let fontSizeFontSize24 = Primitives.Spacing.spacing24
        public static let fontSizeFontSize32 = Primitives.Spacing.spacing32
        public static let fontSizeFontSize40 = Primitives.Spacing.spacing40
        public static let fontSizeFontSize48 = Primitives.Spacing.spacing48
        public static let fontSizeFontSize56 = Primitives.Spacing.spacing56
        public static let fontWeightMedium: Int = 500
        public static let fontWeightRegular: Int = 400
        public static let kerningNone: CGFloat = CGFloat(0.0)
        public static let kerningSpacious: CGFloat = CGFloat(1.0)
        public static let kerningTight: CGFloat = CGFloat(-0.5)
        public static let lineHeightLineHeight16 = Primitives.Spacing.spacing16
        public static let lineHeightLineHeight20 = Primitives.Spacing.spacing20
        public static let lineHeightLineHeight24 = Primitives.Spacing.spacing24
        public static let lineHeightLineHeight28 = Primitives.Spacing.spacing28
        public static let lineHeightLineHeight32 = Primitives.Spacing.spacing32
        public static let lineHeightLineHeight40 = Primitives.Spacing.spacing40
        public static let lineHeightLineHeight48 = Primitives.Spacing.spacing48
    }
}
