// AUTO-GENERATED by Tools/DesignTokenGen — DO NOT EDIT.
// Source: design tokens in SharedUI/DesignTokens. Regenerate: ./Alfie/scripts/generate-design-tokens.sh
// swiftlint:disable all
import SwiftUI

public enum Primitives {
    public enum Border {
        public static let borderWeightDefault: Int = 1
    }
    public enum Colours {
        public static var neutrals0: Color { ThemeColours.current.neutrals0 }
        public static var neutrals100: Color { ThemeColours.current.neutrals100 }
        public static var neutrals200: Color { ThemeColours.current.neutrals200 }
        public static var neutrals300: Color { ThemeColours.current.neutrals300 }
        public static var neutrals400: Color { ThemeColours.current.neutrals400 }
        public static var neutrals500: Color { ThemeColours.current.neutrals500 }
        public static var neutrals600: Color { ThemeColours.current.neutrals600 }
        public static var neutrals700: Color { ThemeColours.current.neutrals700 }
        public static var neutrals800: Color { ThemeColours.current.neutrals800 }
        public static var neutrals900: Color { ThemeColours.current.neutrals900 }
        public static var semanticError100: Color { ThemeColours.current.semanticError100 }
        public static var semanticError200: Color { ThemeColours.current.semanticError200 }
        public static var semanticError300: Color { ThemeColours.current.semanticError300 }
        public static var semanticError400: Color { ThemeColours.current.semanticError400 }
        public static var semanticError500: Color { ThemeColours.current.semanticError500 }
        public static var semanticError600: Color { ThemeColours.current.semanticError600 }
        public static var semanticError700: Color { ThemeColours.current.semanticError700 }
        public static var semanticError800: Color { ThemeColours.current.semanticError800 }
        public static var semanticSuccess100: Color { ThemeColours.current.semanticSuccess100 }
        public static var semanticSuccess200: Color { ThemeColours.current.semanticSuccess200 }
        public static var semanticSuccess300: Color { ThemeColours.current.semanticSuccess300 }
        public static var semanticSuccess400: Color { ThemeColours.current.semanticSuccess400 }
        public static var semanticSuccess500: Color { ThemeColours.current.semanticSuccess500 }
        public static var semanticSuccess600: Color { ThemeColours.current.semanticSuccess600 }
        public static var semanticSuccess700: Color { ThemeColours.current.semanticSuccess700 }
        public static var semanticSuccess800: Color { ThemeColours.current.semanticSuccess800 }
        public static var transparentTransparent: Color { ThemeColours.current.transparentTransparent }
    }
    public enum Spacing {
        public static let spacing0: CGFloat = CGFloat(0.0)
        public static let spacing12: CGFloat = CGFloat(12.0)
        public static let spacing124: CGFloat = CGFloat(124.0)
        public static let spacing14: CGFloat = CGFloat(14.0)
        public static let spacing16: CGFloat = CGFloat(16.0)
        public static let spacing18: CGFloat = CGFloat(18.0)
        public static let spacing2: CGFloat = CGFloat(2.0)
        public static let spacing20: CGFloat = CGFloat(20.0)
        public static let spacing220: CGFloat = CGFloat(220.0)
        public static let spacing24: CGFloat = CGFloat(24.0)
        public static let spacing28: CGFloat = CGFloat(28.0)
        public static let spacing32: CGFloat = CGFloat(32.0)
        public static let spacing4: CGFloat = CGFloat(4.0)
        public static let spacing40: CGFloat = CGFloat(40.0)
        public static let spacing48: CGFloat = CGFloat(48.0)
        public static let spacing56: CGFloat = CGFloat(56.0)
        public static let spacing64: CGFloat = CGFloat(64.0)
        public static let spacing8: CGFloat = CGFloat(8.0)
        public static let spacing80: CGFloat = CGFloat(80.0)
        public static let spacing96: CGFloat = CGFloat(96.0)
    }
    public enum Typography {
        public static let fontFamilyBrand: String = "Libre Baskerville"
        public static let fontFamilyPrimaryAndroid: String = "Roboto"
        public static let fontFamilyPrimaryIos: String = "SF Pro"
        public static let fontFamilyPrimaryWeb: String = "Inter"
        public static let fontSizeFontSize12 = Primitives.Spacing.spacing12
        public static let fontSizeFontSize14 = Primitives.Spacing.spacing14
        public static let fontSizeFontSize16 = Primitives.Spacing.spacing16
        public static let fontSizeFontSize18 = Primitives.Spacing.spacing18
        public static let fontSizeFontSize20 = Primitives.Spacing.spacing20
        public static let fontSizeFontSize24 = Primitives.Spacing.spacing24
        public static let fontSizeFontSize32 = Primitives.Spacing.spacing32
        public static let fontSizeFontSize40 = Primitives.Spacing.spacing40
        public static let fontSizeFontSize48 = Primitives.Spacing.spacing48
        public static let fontSizeFontSize56 = Primitives.Spacing.spacing56
        public static let kerningNone: CGFloat = CGFloat(0.0)
        public static let kerningSpacious: CGFloat = CGFloat(1.0)
        public static let kerningTight: CGFloat = CGFloat(-0.5)
        public static let lineHeightLineHeight16 = Primitives.Spacing.spacing16
        public static let lineHeightLineHeight20 = Primitives.Spacing.spacing20
        public static let lineHeightLineHeight24 = Primitives.Spacing.spacing24
        public static let lineHeightLineHeight28 = Primitives.Spacing.spacing28
        public static let lineHeightLineHeight32 = Primitives.Spacing.spacing32
        public static let lineHeightLineHeight40 = Primitives.Spacing.spacing40
        public static let lineHeightLineHeight48 = Primitives.Spacing.spacing48
    }
}
