// AUTO-GENERATED by Tools/DesignTokenGen — DO NOT EDIT.
// Source: design tokens in SharedUI/DesignTokens. Regenerate: ./Alfie/scripts/generate-design-tokens.sh
// swiftlint:disable all
import CoreGraphics

public enum Sizing {
    public static let iconsIconLarge: CGFloat = Primitives.Spacing.spacing32
    public static let iconsIconMedium: CGFloat = Primitives.Spacing.spacing24
    public static let iconsIconSmall: CGFloat = Primitives.Spacing.spacing16
    public static let iconsIconXlarge: CGFloat = Primitives.Spacing.spacing40
    public static let interactiveSmallPaddingLeftRight: CGFloat = Primitives.Spacing.spacing8
    public static let interactiveSmallPaddingTopBottom: CGFloat = Primitives.Spacing.spacing8
    public static let radiusRounded: CGFloat = CGFloat(1000.0)
    public static let radiusSoft: CGFloat = Primitives.Spacing.spacing4
    public static let radiusStrong: CGFloat = Primitives.Spacing.spacing16
}
