// AUTO-GENERATED by Tools/DesignTokenGen — DO NOT EDIT.
// Source: design tokens in SharedUI/DesignTokens. Regenerate: ./Alfie/scripts/generate-design-tokens.sh
// swiftlint:disable all
import Foundation

public struct FontPalette {
    public let fontFamilyBrand: String
    public let fontFamilyPrimaryAndroid: String
    public let fontFamilyPrimaryIos: String
    public let fontFamilyPrimaryWeb: String

    public init(fontFamilyBrand: String, fontFamilyPrimaryAndroid: String, fontFamilyPrimaryIos: String, fontFamilyPrimaryWeb: String) {
        self.fontFamilyBrand = fontFamilyBrand
        self.fontFamilyPrimaryAndroid = fontFamilyPrimaryAndroid
        self.fontFamilyPrimaryIos = fontFamilyPrimaryIos
        self.fontFamilyPrimaryWeb = fontFamilyPrimaryWeb
    }
}

public enum ThemeFonts {
    public static let alfie = FontPalette(fontFamilyBrand: "Libre Baskerville", fontFamilyPrimaryAndroid: "Roboto", fontFamilyPrimaryIos: "SF Pro", fontFamilyPrimaryWeb: "Inter")
    public static let selffridge = FontPalette(fontFamilyBrand: "Georgia", fontFamilyPrimaryAndroid: "Roboto", fontFamilyPrimaryIos: "Georgia", fontFamilyPrimaryWeb: "Inter")

    /// The active font palette. Set at launch and on each theme switch, before the UI builds.
    public static var current: FontPalette = alfie

    /// Apply by persisted id; unknown ids leave the current palette unchanged.
    public static func apply(id: String) {
        switch id {
        case "alfie-theme": current = alfie
        case "selffridge-theme": current = selffridge
        default: break
        }
    }
}
