// AUTO-GENERATED by Tools/DesignTokenGen — DO NOT EDIT.
// Source: design tokens in SharedUI/DesignTokens. Regenerate: ./Alfie/scripts/generate-design-tokens.sh
// swiftlint:disable all
import SwiftUI

public enum Theme {
    public static var borderSoft: Color { Primitives.Colours.neutrals200 }
    public static var buttonDestructiveBackgroundDestructiveDefault: Color { Primitives.Colours.semanticError600 }
    public static var buttonDestructiveStrokeDestructiveDefault: Color { Primitives.Colours.semanticError600 }
    public static var buttonPrimaryBackgroundPrimaryDefault: Color { Primitives.Colours.neutrals800 }
    public static var buttonSecondaryBackgroundSecondaryDefault: Color { Primitives.Colours.transparentTransparent }
    public static var buttonSecondaryBackgroundSecondaryDisabled: Color { Primitives.Colours.transparentTransparent }
    public static var buttonTerciaryBackgroundTerciaryDefault: Color { Primitives.Colours.transparentTransparent }
    public static var buttonTerciaryBackgroundTerciaryDisabled: Color { Primitives.Colours.transparentTransparent }
    public static var buttonTerciaryStrokeTerciaryDefault: Color { Primitives.Colours.transparentTransparent }
    public static var buttonTerciaryStrokeTerciaryDisabled: Color { Primitives.Colours.transparentTransparent }
    public static var contentContentInvertedPrimary: Color { Primitives.Colours.neutrals0 }
    public static var contentContentInvertedPrimarydisabled: Color { Primitives.Colours.neutrals500 }
    public static var contentContentNegative: Color { Primitives.Colours.semanticError500 }
    public static var contentContentPositive: Color { Primitives.Colours.semanticSuccess400 }
    public static var contentContentPrimary: Color { Primitives.Colours.neutrals800 }
    public static var contentContentPrimaryActive: Color { Primitives.Colours.neutrals0 }
    public static var contentContentPrimaryDisabled: Color { Primitives.Colours.neutrals400 }
    public static var contentContentTerciary: Color { Primitives.Colours.neutrals500 }
    public static var linkLinkPrimaryDefault: Color { Primitives.Colours.neutrals800 }
    public static var linkLinkPrimaryDisabled: Color { Primitives.Colours.neutrals400 }
    public static var linkLinkPrimaryInvertedDefault: Color { Primitives.Colours.neutrals0 }
    public static var linkLinkPrimaryInvertedDisabled: Color { Primitives.Colours.neutrals500 }
    public static var surfaceBackgroundDestructive: Color { Primitives.Colours.semanticError600 }
    public static var surfaceBackgroundInvertedPrimary: Color { Primitives.Colours.neutrals800 }
    public static var surfaceBackgroundNegative: Color { Primitives.Colours.semanticError500 }
    public static var surfaceBackgroundPositive: Color { Primitives.Colours.semanticSuccess600 }
    public static var surfaceBackgroundPrimary: Color { Primitives.Colours.neutrals0 }
    public static var surfaceBackgroundPrimaryActive: Color { Primitives.Colours.neutrals800 }
    public static var surfaceBackgroundTerciary: Color { Primitives.Colours.neutrals300 }
    public static var surfaceForegroundInvertedPrimary: Color { Primitives.Colours.neutrals700 }
    public static var surfaceForegroundPrimary: Color { Primitives.Colours.neutrals100 }
}
