// AUTO-GENERATED by Tools/DesignTokenGen — DO NOT EDIT.
// Source: design tokens in SharedUI/DesignTokens. Regenerate: ./Alfie/scripts/generate-design-tokens.sh
// swiftlint:disable all
import SwiftUI

public enum Theme {
    public static let borderSoft = Primitives.Colours.neutrals200
    public static let buttonDestructiveBackgroundDestructiveDefault = Primitives.Colours.semanticError600
    public static let buttonDestructiveStrokeDestructiveDefault = Primitives.Colours.semanticError600
    public static let buttonPrimaryBackgroundPrimaryDefault = Primitives.Colours.neutrals800
    public static let buttonSecondaryBackgroundSecondaryDefault = Primitives.Colours.transparentTransparent
    public static let buttonSecondaryBackgroundSecondaryDisabled = Primitives.Colours.transparentTransparent
    public static let buttonTerciaryBackgroundTerciaryDefault = Primitives.Colours.transparentTransparent
    public static let buttonTerciaryBackgroundTerciaryDisabled = Primitives.Colours.transparentTransparent
    public static let buttonTerciaryStrokeTerciaryDefault = Primitives.Colours.transparentTransparent
    public static let buttonTerciaryStrokeTerciaryDisabled = Primitives.Colours.transparentTransparent
    public static let contentContentInvertedPrimary = Primitives.Colours.neutrals0
    public static let contentContentInvertedPrimarydisabled = Primitives.Colours.neutrals500
    public static let contentContentNegative = Primitives.Colours.semanticError500
    public static let contentContentPositive = Primitives.Colours.semanticSuccess400
    public static let contentContentPrimary = Primitives.Colours.neutrals800
    public static let contentContentPrimaryActive = Primitives.Colours.neutrals0
    public static let contentContentPrimaryDisabled = Primitives.Colours.neutrals400
    public static let contentContentTerciary = Primitives.Colours.neutrals500
    public static let linkLinkPrimaryDefault = Primitives.Colours.neutrals800
    public static let linkLinkPrimaryDisabled = Primitives.Colours.neutrals400
    public static let linkLinkPrimaryInvertedDefault = Primitives.Colours.neutrals0
    public static let linkLinkPrimaryInvertedDisabled = Primitives.Colours.neutrals500
    public static let surfaceBackgroundDestructive = Primitives.Colours.semanticError600
    public static let surfaceBackgroundInvertedPrimary = Primitives.Colours.neutrals800
    public static let surfaceBackgroundNegative = Primitives.Colours.semanticError500
    public static let surfaceBackgroundPositive = Primitives.Colours.semanticSuccess600
    public static let surfaceBackgroundPrimary = Primitives.Colours.neutrals0
    public static let surfaceBackgroundPrimaryActive = Primitives.Colours.neutrals800
    public static let surfaceBackgroundTerciary = Primitives.Colours.neutrals300
    public static let surfaceForegroundInvertedPrimary = Primitives.Colours.neutrals700
    public static let surfaceForegroundPrimary = Primitives.Colours.neutrals100
}
