// AUTO-GENERATED by Tools/DesignTokenGen — DO NOT EDIT.
// Source: design tokens in SharedUI/DesignTokens. Regenerate: ./Alfie/scripts/generate-design-tokens.sh
// swiftlint:disable all
import CoreGraphics

public struct TypographyStyle {
    public let fontFamily: String
    public let fontWeight: Int
    public let fontSize: CGFloat
    public let lineHeight: CGFloat
    public let letterSpacing: CGFloat

    public init(fontFamily: String, fontWeight: Int, fontSize: CGFloat, lineHeight: CGFloat, letterSpacing: CGFloat) {
        self.fontFamily = fontFamily
        self.fontWeight = fontWeight
        self.fontSize = fontSize
        self.lineHeight = lineHeight
        self.letterSpacing = letterSpacing
    }
}

public enum Typography {
    public enum Body {
        public static var large: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyPrimaryIos,
                fontWeight: 400,
                fontSize: Primitives.Spacing.spacing18,
                lineHeight: Primitives.Spacing.spacing28,
                letterSpacing: Primitives.Typography.kerningNone
            )
        }
        public static var medium: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyPrimaryIos,
                fontWeight: 400,
                fontSize: Primitives.Spacing.spacing16,
                lineHeight: Primitives.Spacing.spacing24,
                letterSpacing: Primitives.Typography.kerningNone
            )
        }
        public static var mediumStrikethrough: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyPrimaryIos,
                fontWeight: 400,
                fontSize: Primitives.Spacing.spacing16,
                lineHeight: Primitives.Spacing.spacing24,
                letterSpacing: Primitives.Typography.kerningNone
            )
        }
        public static var small: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyPrimaryIos,
                fontWeight: 400,
                fontSize: Primitives.Spacing.spacing12,
                lineHeight: Primitives.Spacing.spacing16,
                letterSpacing: Primitives.Typography.kerningNone
            )
        }
    }
    public enum Display {
        public static var large: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyBrand,
                fontWeight: 400,
                fontSize: Primitives.Spacing.spacing24,
                lineHeight: Primitives.Spacing.spacing40,
                letterSpacing: Primitives.Typography.kerningNone
            )
        }
        public static var medium: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyBrand,
                fontWeight: 400,
                fontSize: Primitives.Spacing.spacing20,
                lineHeight: Primitives.Spacing.spacing32,
                letterSpacing: Primitives.Typography.kerningNone
            )
        }
        public static var small: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyBrand,
                fontWeight: 400,
                fontSize: Primitives.Spacing.spacing18,
                lineHeight: Primitives.Spacing.spacing28,
                letterSpacing: Primitives.Typography.kerningNone
            )
        }
    }
    public enum Heading {
        public static var large: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyPrimaryIos,
                fontWeight: 500,
                fontSize: Primitives.Spacing.spacing32,
                lineHeight: Primitives.Spacing.spacing40,
                letterSpacing: Primitives.Typography.kerningTight
            )
        }
        public static var medium: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyPrimaryIos,
                fontWeight: 500,
                fontSize: Primitives.Spacing.spacing24,
                lineHeight: Primitives.Spacing.spacing32,
                letterSpacing: Primitives.Typography.kerningTight
            )
        }
        public static var small: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyPrimaryIos,
                fontWeight: 500,
                fontSize: Primitives.Spacing.spacing20,
                lineHeight: Primitives.Spacing.spacing28,
                letterSpacing: Primitives.Typography.kerningTight
            )
        }
        public static var xSmall: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyPrimaryIos,
                fontWeight: 500,
                fontSize: Primitives.Spacing.spacing16,
                lineHeight: Primitives.Spacing.spacing20,
                letterSpacing: Primitives.Typography.kerningTight
            )
        }
    }
    public enum Label {
        public static var small: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyPrimaryIos,
                fontWeight: 400,
                fontSize: Primitives.Spacing.spacing12,
                lineHeight: Primitives.Spacing.spacing16,
                letterSpacing: Primitives.Typography.kerningNone
            )
        }
        public static var smallBold: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyPrimaryIos,
                fontWeight: 500,
                fontSize: Primitives.Spacing.spacing12,
                lineHeight: Primitives.Spacing.spacing16,
                letterSpacing: Primitives.Typography.kerningNone
            )
        }
    }
    public enum Link {
        public static var medium: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyPrimaryIos,
                fontWeight: 500,
                fontSize: Primitives.Spacing.spacing16,
                lineHeight: Primitives.Spacing.spacing24,
                letterSpacing: Primitives.Typography.kerningNone
            )
        }
        public static var small: TypographyStyle {
            TypographyStyle(
                fontFamily: Primitives.Typography.fontFamilyPrimaryIos,
                fontWeight: 500,
                fontSize: Primitives.Spacing.spacing12,
                lineHeight: Primitives.Spacing.spacing16,
                letterSpacing: Primitives.Typography.kerningNone
            )
        }
    }
}
