#!/bin/bash
#
# sync-bff-schema.sh — refresh the iOS app's committed copy of the Alfie BFF GraphQL schema.
#
# Steps:
#   1. Locate the Alfie-BFF repo (sibling checkout by default; override via ALFIE_BFF_PATH).
#   2. Check out `main` and pull the latest code in the BFF repo. The script does change
#      the BFF repo's checked-out branch and HEAD, but never commits or pushes to it.
#   3. Copy the BFF's generated schema (src/schema.gql) into this repo as the committed
#      Apollo codegen input: AlfieKit/Sources/BFFGraph/CodeGen/Schema/schema.graphqls
#   4. Run Apollo codegen.
#
# The schema is committed in this repo so codegen and builds are self-contained — they
# do not depend on the BFF repo being present or on a running BFF. Re-run this script
# whenever the BFF schema changes.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IOS_REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Alfie-BFF repo location. Defaults to a sibling of the iOS repo; override with ALFIE_BFF_PATH.
BFF_REPO_PATH="${ALFIE_BFF_PATH:-${IOS_REPO_ROOT}/../Alfie-BFF}"
BFF_SCHEMA_SRC="${BFF_REPO_PATH}/src/schema.gql"
IOS_SCHEMA_DEST="${IOS_REPO_ROOT}/Alfie/AlfieKit/Sources/BFFGraph/CodeGen/Schema/schema.graphqls"

echo "🔄 Syncing BFF GraphQL schema"
echo "   BFF repo: ${BFF_REPO_PATH}"
echo ""

# --- 1. Validate the BFF repo ------------------------------------------------
if [ ! -d "${BFF_REPO_PATH}/.git" ]; then
    echo "❌ Alfie-BFF repo not found at: ${BFF_REPO_PATH}"
    echo "   Clone it next to the iOS repo, or set ALFIE_BFF_PATH to its location:"
    echo "     ALFIE_BFF_PATH=/path/to/Alfie-BFF $0"
    exit 1
fi

# --- 2. Check out main & pull latest (no commits/pushes to the BFF repo) -----
# Only tracked-file modifications matter — `git checkout`/`pull` never touch untracked
# files (build output, .env, node_modules, etc.), so those must not block the sync.
if [ -n "$(git -C "${BFF_REPO_PATH}" status --porcelain --untracked-files=no)" ]; then
    echo "❌ The Alfie-BFF repo has uncommitted changes to tracked files."
    echo "   Commit or stash them first, then re-run. (Untracked files are fine.)"
    exit 1
fi

echo "📥 Updating BFF repo (checkout main, pull)..."
git -C "${BFF_REPO_PATH}" checkout main
git -C "${BFF_REPO_PATH}" pull --ff-only
echo ""

# --- 3. Copy the schema into this repo ---------------------------------------
if [ ! -f "${BFF_SCHEMA_SRC}" ]; then
    echo "❌ BFF schema not found at: ${BFF_SCHEMA_SRC}"
    echo "   Expected the BFF's generated schema (autoSchemaFile) to be committed."
    exit 1
fi

cp "${BFF_SCHEMA_SRC}" "${IOS_SCHEMA_DEST}"
# Normalise trailing newline (the BFF's autogenerated schema.gql does not terminate with one).
[ -n "$(tail -c1 "${IOS_SCHEMA_DEST}")" ] && printf '\n' >> "${IOS_SCHEMA_DEST}"
echo "✅ Schema copied → ${IOS_SCHEMA_DEST#"${IOS_REPO_ROOT}/"}"
echo ""

# --- 4. Run Apollo codegen ---------------------------------------------------
echo "⚙️  Running Apollo codegen..."
( cd "${SCRIPT_DIR}" && ./run-apollo-codegen.sh )

echo ""
echo "================================================================"
echo "✅ BFF schema sync complete."
echo "   Updated: ${IOS_SCHEMA_DEST#"${IOS_REPO_ROOT}/"}"
echo "   Apollo types regenerated."
echo "================================================================"
