import Foundation

/// Emits committed Swift from the resolved token graph. Output is deterministic (everything sorted,
/// no timestamps) and preserves the reference graph: semantic / sizing / typography tokens emit as
/// references to `Primitives.*` symbols; only primitives hold concrete literals.
public struct Emitter {
    let loaded: LoadedTokens
    let resolver: Resolver

    public init(loaded: LoadedTokens, resolver: Resolver) {
        self.loaded = loaded
        self.resolver = resolver
    }

    static let header = """
    // AUTO-GENERATED by Tools/DesignTokenGen — DO NOT EDIT.
    // Source: design tokens in SharedUI/DesignTokens. Regenerate: ./Alfie/scripts/generate-design-tokens.sh
    // swiftlint:disable all
    """

    /// filename → file contents. Stable set of five files.
    public func emit() throws -> [String: String] {
        [
            "Primitives+Generated.swift": try emitPrimitives(),
            "Theme+Generated.swift": try emitTheme(),
            "Sizing+Generated.swift": try emitSizing(),
            "Typography+Generated.swift": try emitTypography(),
            "ThemeColours+Generated.swift": try emitThemeColours(),
            "ThemeFonts+Generated.swift": try emitFonts(),
        ]
    }

    // MARK: - Primitives (concrete literals, grouped by first name segment)

    private func emitPrimitives() throws -> String {
        let primitives = Array(loaded.primitiveValues.values)
        let grouped = Dictionary(grouping: primitives, by: { firstSegment($0.name) })
        var body = ""
        for group in grouped.keys.sorted() {
            let members = grouped[group]!.sorted { $0.name < $1.name }
            try SwiftIdentifier.assertNoCollisions(members.map(\.name), dropPrefix: group)
            body += "    public enum \(upperCamel(group)) {\n"
            for token in members {
                let id = SwiftIdentifier.make(token.name, dropPrefix: group)
                if group == coloursGroup {
                    // Colours are theme-swappable: forward to the active palette instead of a fixed
                    // literal, so a runtime theme switch (+ soft-reboot) re-renders every call site
                    // unchanged. The concrete literals live in `ThemeColours` (one per theme).
                    body += "        public static var \(id): Color { ThemeColours.current.\(id) }\n"
                } else if case .fontFamily = token.value {
                    // Font families are theme-swappable too: forward to the active font palette so a
                    // theme switch re-renders text. The concrete literals live in `ThemeFonts`.
                    body += "        public static var \(id): String { ThemeFonts.current.\(id) }\n"
                } else {
                    // Most primitives are concrete; a few reference another primitive
                    // (e.g. a font-size aliased to a spacing value) — keep that as a symbol reference.
                    body += "        public static let \(id)\(annotation(token.value)) = \(try valueOrPrimitiveRef(token))\n"
                }
            }
            body += "    }\n"
        }
        return """
        \(Self.header)
        import SwiftUI

        public enum Primitives {
        \(body)}
        """
    }

    // MARK: - Theme (semantic → primitive references)

    private func emitTheme() throws -> String {
        let theme = loaded.map.values.filter { $0.file.hasPrefix("theme.") }.sorted { $0.name < $1.name }
        try SwiftIdentifier.assertNoCollisions(theme.map(\.name))
        var body = ""
        for token in theme {
            let id = SwiftIdentifier.make(token.name)
            // Computed (not `static let`): semantic colours forward to `Primitives.Colours` which is
            // theme-swappable, so a `let` would cache the launch theme and go stale after a switch.
            body += "    public static var \(id): Color { \(try valueOrPrimitiveRef(token)) }\n"
        }
        return """
        \(Self.header)
        import SwiftUI

        public enum Theme {
        \(body)}
        """
    }

    // MARK: - ThemeColours (per-theme colour palettes + active holder)

    /// Emits the swappable colour layer that `Primitives.Colours` forwards to:
    /// - `ColourPalette`: one `Color` per colour primitive (schema = the base theme's colours).
    /// - `ThemeColours`: a concrete palette per theme (literals) + the mutable `current` holder.
    /// - `AppTheme`: `String`-backed, `CaseIterable` ids for pickers/persistence, mapped to palettes.
    /// Every theme must define the full base colour schema — a gap fails the build (catches drift).
    private func emitThemeColours() throws -> String {
        // Colour source: explicit per-theme palettes when present, else a single base palette derived
        // from the primitive colours (keeps `emit()` valid for minimal/hand-built inputs).
        var colourThemes = loaded.colourThemes
        if colourThemes.isEmpty {
            let baseColours = loaded.primitiveValues.filter { $0.value.value.isColour }
            if !baseColours.isEmpty { colourThemes = [loaded.baseTheme: baseColours] }
        }
        let themeIDs = colourThemes.keys.sorted()
        // A token set with no colours at all → a valid, empty holder (nothing forwards to it).
        guard !themeIDs.isEmpty else { return emptyThemeColoursFile() }

        let base = colourThemes[loaded.baseTheme] != nil ? loaded.baseTheme : themeIDs[0]
        let baseColours = colourThemes[base]!
        let members = baseColours.keys.sorted().map { (name: $0, id: SwiftIdentifier.make($0, dropPrefix: coloursGroup)) }
        try SwiftIdentifier.assertNoCollisions(baseColours.keys.sorted(), dropPrefix: coloursGroup)
        // Guard the one identifier surface that isn't a token name: theme ids → palette/case names.
        try SwiftIdentifier.assertNoCollisions(themeIDs.map(themeVarName))

        // ColourPalette struct: one stored Color per colour id.
        let structFields = members.map { "    public let \($0.id): Color" }.joined(separator: "\n")
        let initParams = members.map { "\($0.id): Color" }.joined(separator: ", ")
        let initBody = members.map { "        self.\($0.id) = \($0.id)" }.joined(separator: "\n")

        // One concrete palette per theme (literal colours).
        var instances = ""
        for themeId in themeIDs {
            let colours = colourThemes[themeId]!
            let args = try members.map { member -> String in
                guard let token = colours[member.name] else {
                    throw DesignTokenError.malformedToken(
                        name: "\(themeId)/\(member.name)",
                        reason: "theme '\(themeId)' is missing colour '\(member.name)' defined in base '\(base)'"
                    )
                }
                return "\(member.id): \(try literal(token.value, name: member.name))"
            }.joined(separator: ", ")
            instances += "    public static let \(themeVarName(themeId)) = ColourPalette(\(args))\n"
        }

        // AppTheme enum: ids for pickers/persistence, mapped to their palette.
        let appCases = themeIDs.map { "    case \(themeVarName($0)) = \(String(reflecting: $0))" }.joined(separator: "\n")
        let appPaletteCases = themeIDs.map { "        case .\(themeVarName($0)): return ThemeColours.\(themeVarName($0))" }.joined(separator: "\n")

        return """
        \(Self.header)
        import SwiftUI

        public struct ColourPalette {
        \(structFields)

            public init(\(initParams)) {
        \(initBody)
            }
        }

        public enum AppTheme: String, CaseIterable {
        \(appCases)

            public var palette: ColourPalette {
                switch self {
        \(appPaletteCases)
                }
            }
        }

        public enum ThemeColours {
        \(instances)
            /// The active palette. Set once at launch (and on each theme switch) before the UI builds.
            public static var current: ColourPalette = \(themeVarName(base))

            public static func apply(_ theme: AppTheme) { current = theme.palette }

            /// Apply by persisted id; unknown ids leave the current palette unchanged.
            public static func apply(id: String) {
                if let theme = AppTheme(rawValue: id) { current = theme.palette }
            }
        }
        """
    }

    /// Valid, empty colour layer for token sets that define no colours (keeps the emitted file set
    /// stable). Nothing forwards to it, so an empty palette/holder is harmless.
    private func emptyThemeColoursFile() -> String {
        """
        \(Self.header)
        import SwiftUI

        public struct ColourPalette {
            public init() {}
        }

        // No themes → a case-less enum. It must NOT declare a raw type or `CaseIterable`
        // (a no-case enum can't synthesize `RawRepresentable`/`allCases`).
        public enum AppTheme {
        }

        public enum ThemeColours {
            public static var current = ColourPalette()

            public static func apply(_ theme: AppTheme) {}

            public static func apply(id: String) {}
        }
        """
    }

    // MARK: - ThemeFonts (per-theme font-family palettes + active holder)

    /// Emits the swappable font layer that `Primitives.Typography` font families forward to, mirroring
    /// `ThemeColours`. Unlike colours (strict full schema per theme), a theme may override only some
    /// font families — undefined ones fall back to the base theme, since most families (platform
    /// defaults) are theme-invariant and only the brand font typically changes.
    private func emitFonts() throws -> String {
        var fontThemes = loaded.fontThemes.filter { !$0.value.isEmpty }
        if fontThemes.isEmpty {
            let baseFonts = loaded.primitiveValues.filter { if case .fontFamily = $0.value.value { return true }; return false }
            if !baseFonts.isEmpty { fontThemes = [loaded.baseTheme: baseFonts] }
        }
        let themeIDs = fontThemes.keys.sorted()
        // A token set with no font families → a valid, empty holder (nothing forwards to it).
        guard !themeIDs.isEmpty else { return emptyThemeFontsFile() }

        let base = fontThemes[loaded.baseTheme] != nil ? loaded.baseTheme : themeIDs[0]
        let baseFonts = fontThemes[base]!
        let members = baseFonts.keys.sorted().map { (name: $0, id: SwiftIdentifier.make($0, dropPrefix: fontGroup)) }
        try SwiftIdentifier.assertNoCollisions(baseFonts.keys.sorted(), dropPrefix: fontGroup)
        try SwiftIdentifier.assertNoCollisions(themeIDs.map(themeVarName))

        let structFields = members.map { "    public let \($0.id): String" }.joined(separator: "\n")
        let initParams = members.map { "\($0.id): String" }.joined(separator: ", ")
        let initBody = members.map { "        self.\($0.id) = \($0.id)" }.joined(separator: "\n")

        // One concrete palette per theme; a family the theme doesn't override falls back to base.
        var instances = ""
        for themeId in themeIDs {
            let fonts = fontThemes[themeId]!
            let args = try members.map { member -> String in
                let token = fonts[member.name] ?? baseFonts[member.name]!
                return "\(member.id): \(try literal(token.value, name: member.name))"
            }.joined(separator: ", ")
            instances += "    public static let \(themeVarName(themeId)) = FontPalette(\(args))\n"
        }
        let applyCases = themeIDs
            .map { "        case \(String(reflecting: $0)): current = \(themeVarName($0))" }
            .joined(separator: "\n")

        return """
        \(Self.header)
        import Foundation

        public struct FontPalette {
        \(structFields)

            public init(\(initParams)) {
        \(initBody)
            }
        }

        public enum ThemeFonts {
        \(instances)
            /// The active font palette. Set at launch and on each theme switch, before the UI builds.
            public static var current: FontPalette = \(themeVarName(base))

            /// Apply by persisted id; unknown ids leave the current palette unchanged.
            public static func apply(id: String) {
                switch id {
        \(applyCases)
                default: break
                }
            }
        }
        """
    }

    /// Valid, empty font layer for token sets that define no font families (keeps the emitted file set
    /// stable). Nothing forwards to it, so an empty palette/holder is harmless.
    private func emptyThemeFontsFile() -> String {
        """
        \(Self.header)
        import Foundation

        public struct FontPalette {
            public init() {}
        }

        public enum ThemeFonts {
            public static var current = FontPalette()

            public static func apply(id: String) {}
        }
        """
    }

    // MARK: - Sizing (mix of primitive references and concrete literals)

    private func emitSizing() throws -> String {
        let sizing = loaded.map.values.filter { $0.file.hasPrefix("sizing.") }.sorted { $0.name < $1.name }
        try SwiftIdentifier.assertNoCollisions(sizing.map(\.name))
        var body = ""
        for token in sizing {
            let id = SwiftIdentifier.make(token.name)
            body += "    public static let \(id): CGFloat = \(try valueOrPrimitiveRef(token))\n"
        }
        return """
        \(Self.header)
        import CoreGraphics

        public enum Sizing {
        \(body)}
        """
    }

    // MARK: - Typography (composite styles, nested by first segment → Typography.display.large)

    private func emitTypography() throws -> String {
        let styles = loaded.map.values.filter { $0.file.hasPrefix("typography.styles") }.sorted { $0.name < $1.name }
        let grouped = Dictionary(grouping: styles, by: { firstSegment($0.name) })
        var body = ""
        for group in grouped.keys.sorted() {
            let members = grouped[group]!.sorted { $0.name < $1.name }
            let memberNames = members.map { stripFirstSegment($0.name) }
            try SwiftIdentifier.assertNoCollisions(memberNames)
            body += "    public enum \(upperCamel(group)) {\n"
            for token in members {
                guard case .typography(let typo) = token.value else { continue }
                let id = SwiftIdentifier.make(stripFirstSegment(token.name))
                // Computed (not `static let`): `fontFamily` forwards to the theme-swappable
                // `Primitives.Typography` / `ThemeFonts`, so a `let` would snapshot the launch font
                // and go stale after a theme switch.
                body += "        public static var \(id): TypographyStyle {\n"
                body += "            TypographyStyle(\n"
                body += "                fontFamily: \(try fieldRef(typo.fontFamily)),\n"
                body += "                fontWeight: \(try fieldRef(typo.fontWeight)),\n"
                body += "                fontSize: \(try fieldRef(typo.fontSize)),\n"
                body += "                lineHeight: \(try fieldRef(typo.lineHeight)),\n"
                body += "                letterSpacing: \(try fieldRef(typo.letterSpacing))\n"
                body += "            )\n"
                body += "        }\n"
            }
            body += "    }\n"
        }
        return """
        \(Self.header)
        import CoreGraphics

        public struct TypographyStyle {
            public let fontFamily: String
            public let fontWeight: Int
            public let fontSize: CGFloat
            public let lineHeight: CGFloat
            public let letterSpacing: CGFloat

            public init(fontFamily: String, fontWeight: Int, fontSize: CGFloat, lineHeight: CGFloat, letterSpacing: CGFloat) {
                self.fontFamily = fontFamily
                self.fontWeight = fontWeight
                self.fontSize = fontSize
                self.lineHeight = lineHeight
                self.letterSpacing = letterSpacing
            }
        }

        public enum Typography {
        \(body)}
        """
    }

    // MARK: - Reference / literal helpers

    /// A token whose value is a reference → `Primitives.*` symbol; otherwise its concrete literal.
    private func valueOrPrimitiveRef(_ token: Token) throws -> String {
        guard case .reference(let target) = token.value else {
            return try literal(token.value, name: token.name)
        }
        return try primitiveRefOrLiteral(target)
    }

    private func fieldRef(_ value: TokenValue) throws -> String {
        switch value {
        case .reference(let target):
            return try primitiveRefOrLiteral(target)
        case .fontWeight(let weight):
            return "\(weight.cssValue)"
        default:
            return try literal(value, name: "<inline>")
        }
    }

    /// Resolve a reference target to its terminal: emit a `Primitives.*` symbol if it lands on a
    /// primitive, else inline the concrete literal (keeps the reference graph where one exists).
    private func primitiveRefOrLiteral(_ target: String) throws -> String {
        guard let terminal = try resolver.resolvedConcrete(target) else {
            // resolvedConcrete returns nil only for an allow-listed broken ref — which an *emitted*
            // surface should never reach (broken refs live in the non-emitted intermediate tokens).
            throw DesignTokenError.brokenReferenceInOutput(target: target)
        }
        if resolver.isPrimitive(terminal.name) {
            let group = upperCamel(firstSegment(terminal.name))
            let id = SwiftIdentifier.make(terminal.name, dropPrefix: firstSegment(terminal.name))
            return "Primitives.\(group).\(id)"
        }
        return try literal(terminal.value, name: terminal.name)
    }

    private func literal(_ value: TokenValue, name: String) throws -> String {
        switch value {
        case .color(let comps):
            guard comps.count >= 3 else { throw DesignTokenError.malformedToken(name: name, reason: "color needs ≥3 components") }
            let a = comps.count > 3 ? comps[3] : 1.0
            return "Color(.sRGB, red: \(num(comps[0])), green: \(num(comps[1])), blue: \(num(comps[2])), opacity: \(num(a)))"
        case .dimension(let v, _):
            return "CGFloat(\(num(v)))"
        case .fontFamily(let family):
            return String(reflecting: family)   // properly escaped Swift string literal
        case .fontWeight(let weight):
            return "\(weight.cssValue)"
        case .string(let s):
            return String(reflecting: s)         // properly escaped Swift string literal
        case .typography:
            throw DesignTokenError.malformedToken(name: name, reason: "typography literal unsupported in this position")
        case .reference(let target):
            throw DesignTokenError.malformedToken(name: name, reason: "unresolved reference '{\(target)}'")
        }
    }

    private func annotation(_ value: TokenValue) -> String {
        switch value {
        case .color: return ""               // inferred SwiftUI.Color
        case .dimension: return ": CGFloat"
        case .fontFamily, .string: return ": String"
        case .fontWeight: return ": Int"
        case .typography, .reference: return ""
        }
    }

    // MARK: - Name helpers

    /// The primitives group whose values are theme-swappable (emitted as forwarders, not literals).
    private var coloursGroup: String { "colours" }

    /// The primitives group holding font families (the segment prefix dropped from `ThemeFonts`
    /// palette identifiers). Every `fontFamily` primitive is named `typography-font-family-*`.
    private var fontGroup: String { "typography" }

    /// Theme id → Swift identifier for its palette/case, dropping a trailing `-theme`
    /// (`alfie-theme` → `alfie`, `selffridge-theme` → `selffridge`).
    private func themeVarName(_ themeId: String) -> String {
        let suffix = "-theme"
        let stripped = themeId.hasSuffix(suffix) ? String(themeId.dropLast(suffix.count)) : themeId
        return SwiftIdentifier.make(stripped)
    }

    private func firstSegment(_ name: String) -> String { String(name.split(separator: "-").first ?? "") }
    private func stripFirstSegment(_ name: String) -> String {
        name.split(separator: "-").dropFirst().joined(separator: "-")
    }
    private func upperCamel(_ s: String) -> String {
        s.split(separator: "-").map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
    }
    /// Deterministic, locale-independent number formatting (Swift's shortest round-trippable form).
    private func num(_ d: Double) -> String { "\(d)" }
}
