import Foundation

/// Emits committed Swift from the resolved token graph. Output is deterministic (everything sorted,
/// no timestamps) and preserves the reference graph: semantic / sizing / typography tokens emit as
/// references to `Primitives.*` symbols; only primitives hold concrete literals.
public struct Emitter {
    let loaded: LoadedTokens
    let resolver: Resolver

    public init(loaded: LoadedTokens, resolver: Resolver) {
        self.loaded = loaded
        self.resolver = resolver
    }

    static let header = """
    // AUTO-GENERATED by Tools/DesignTokenGen — DO NOT EDIT.
    // Source: design tokens in SharedUI/DesignTokens. Regenerate: ./Alfie/scripts/generate-design-tokens.sh
    // swiftlint:disable all
    """

    /// filename → file contents. Stable set of four files.
    public func emit() throws -> [String: String] {
        [
            "Primitives+Generated.swift": try emitPrimitives(),
            "Theme+Generated.swift": try emitTheme(),
            "Sizing+Generated.swift": try emitSizing(),
            "Typography+Generated.swift": try emitTypography(),
        ]
    }

    // MARK: - Primitives (concrete literals, grouped by first name segment)

    private func emitPrimitives() throws -> String {
        let primitives = Array(loaded.primitiveValues.values)
        let grouped = Dictionary(grouping: primitives, by: { firstSegment($0.name) })
        var body = ""
        for group in grouped.keys.sorted() {
            let members = grouped[group]!.sorted { $0.name < $1.name }
            try SwiftIdentifier.assertNoCollisions(members.map(\.name), dropPrefix: group)
            body += "    public enum \(upperCamel(group)) {\n"
            for token in members {
                let id = SwiftIdentifier.make(token.name, dropPrefix: group)
                // Most primitives are concrete; a few reference another primitive
                // (e.g. a font-size aliased to a spacing value) — keep that as a symbol reference.
                body += "        public static let \(id)\(annotation(token.value)) = \(try valueOrPrimitiveRef(token))\n"
            }
            body += "    }\n"
        }
        return """
        \(Self.header)
        import SwiftUI

        public enum Primitives {
        \(body)}
        """
    }

    // MARK: - Theme (semantic → primitive references)

    private func emitTheme() throws -> String {
        let theme = loaded.map.values.filter { $0.file.hasPrefix("theme.") }.sorted { $0.name < $1.name }
        try SwiftIdentifier.assertNoCollisions(theme.map(\.name))
        var body = ""
        for token in theme {
            let id = SwiftIdentifier.make(token.name)
            body += "    public static let \(id) = \(try valueOrPrimitiveRef(token))\n"
        }
        return """
        \(Self.header)
        import SwiftUI

        public enum Theme {
        \(body)}
        """
    }

    // MARK: - Sizing (mix of primitive references and concrete literals)

    private func emitSizing() throws -> String {
        let sizing = loaded.map.values.filter { $0.file.hasPrefix("sizing.") }.sorted { $0.name < $1.name }
        try SwiftIdentifier.assertNoCollisions(sizing.map(\.name))
        var body = ""
        for token in sizing {
            let id = SwiftIdentifier.make(token.name)
            body += "    public static let \(id): CGFloat = \(try valueOrPrimitiveRef(token))\n"
        }
        return """
        \(Self.header)
        import CoreGraphics

        public enum Sizing {
        \(body)}
        """
    }

    // MARK: - Typography (composite styles, nested by first segment → Typography.display.large)

    private func emitTypography() throws -> String {
        let styles = loaded.map.values.filter { $0.file.hasPrefix("typography.styles") }.sorted { $0.name < $1.name }
        let grouped = Dictionary(grouping: styles, by: { firstSegment($0.name) })
        var body = ""
        for group in grouped.keys.sorted() {
            let members = grouped[group]!.sorted { $0.name < $1.name }
            let memberNames = members.map { stripFirstSegment($0.name) }
            try SwiftIdentifier.assertNoCollisions(memberNames)
            body += "    public enum \(upperCamel(group)) {\n"
            for token in members {
                guard case .typography(let typo) = token.value else { continue }
                let id = SwiftIdentifier.make(stripFirstSegment(token.name))
                body += "        public static let \(id) = TypographyStyle(\n"
                body += "            fontFamily: \(try fieldRef(typo.fontFamily)),\n"
                body += "            fontWeight: \(try fieldRef(typo.fontWeight)),\n"
                body += "            fontSize: \(try fieldRef(typo.fontSize)),\n"
                body += "            lineHeight: \(try fieldRef(typo.lineHeight)),\n"
                body += "            letterSpacing: \(try fieldRef(typo.letterSpacing))\n"
                body += "        )\n"
            }
            body += "    }\n"
        }
        return """
        \(Self.header)
        import CoreGraphics

        public struct TypographyStyle {
            public let fontFamily: String
            public let fontWeight: Int
            public let fontSize: CGFloat
            public let lineHeight: CGFloat
            public let letterSpacing: CGFloat
        }

        public enum Typography {
        \(body)}
        """
    }

    // MARK: - Reference / literal helpers

    /// A token whose value is a reference → `Primitives.*` symbol; otherwise its concrete literal.
    private func valueOrPrimitiveRef(_ token: Token) throws -> String {
        guard case .reference(let target) = token.value else {
            return try literal(token.value, name: token.name)
        }
        return try primitiveRefOrLiteral(target)
    }

    private func fieldRef(_ value: TokenValue) throws -> String {
        switch value {
        case .reference(let target):
            return try primitiveRefOrLiteral(target)
        case .fontWeight(let weight):
            return "\(weight.cssValue)"
        default:
            return try literal(value, name: "<inline>")
        }
    }

    /// Resolve a reference target to its terminal: emit a `Primitives.*` symbol if it lands on a
    /// primitive, else inline the concrete literal (keeps the reference graph where one exists).
    private func primitiveRefOrLiteral(_ target: String) throws -> String {
        guard let terminal = try resolver.resolvedConcrete(target) else {
            // resolvedConcrete returns nil only for an allow-listed broken ref — which an *emitted*
            // surface should never reach (broken refs live in the non-emitted intermediate tokens).
            throw DesignTokenError.brokenReferenceInOutput(target: target)
        }
        if resolver.isPrimitive(terminal.name) {
            let group = upperCamel(firstSegment(terminal.name))
            let id = SwiftIdentifier.make(terminal.name, dropPrefix: firstSegment(terminal.name))
            return "Primitives.\(group).\(id)"
        }
        return try literal(terminal.value, name: terminal.name)
    }

    private func literal(_ value: TokenValue, name: String) throws -> String {
        switch value {
        case .color(let comps):
            guard comps.count >= 3 else { throw DesignTokenError.malformedToken(name: name, reason: "color needs ≥3 components") }
            let a = comps.count > 3 ? comps[3] : 1.0
            return "Color(.sRGB, red: \(num(comps[0])), green: \(num(comps[1])), blue: \(num(comps[2])), opacity: \(num(a)))"
        case .dimension(let v, _):
            return "CGFloat(\(num(v)))"
        case .fontFamily(let family):
            return String(reflecting: family)   // properly escaped Swift string literal
        case .fontWeight(let weight):
            return "\(weight.cssValue)"
        case .string(let s):
            return String(reflecting: s)         // properly escaped Swift string literal
        case .typography:
            throw DesignTokenError.malformedToken(name: name, reason: "typography literal unsupported in this position")
        case .reference(let target):
            throw DesignTokenError.malformedToken(name: name, reason: "unresolved reference '{\(target)}'")
        }
    }

    private func annotation(_ value: TokenValue) -> String {
        switch value {
        case .color: return ""               // inferred SwiftUI.Color
        case .dimension: return ": CGFloat"
        case .fontFamily, .string: return ": String"
        case .fontWeight: return ": Int"
        case .typography, .reference: return ""
        }
    }

    // MARK: - Name helpers

    private func firstSegment(_ name: String) -> String { String(name.split(separator: "-").first ?? "") }
    private func stripFirstSegment(_ name: String) -> String {
        name.split(separator: "-").dropFirst().joined(separator: "-")
    }
    private func upperCamel(_ s: String) -> String {
        s.split(separator: "-").map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
    }
    /// Deterministic, locale-independent number formatting (Swift's shortest round-trippable form).
    private func num(_ d: Double) -> String { "\(d)" }
}
