---
name: Alfie CI/CD

on:
  push:
    branches:
      - main
      - release/**
  workflow_dispatch:

env:
  DEVELOPER_DIR: "/Applications/Xcode_16.app/Contents/Developer"

jobs:
  branch-validation:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Linting, Analysis, and Tests
        run: fastlane validate_branch
        env:
          IOS_DESTINATION: ${{ env.IOS_DESTINATION }}

  testflight-build:
    needs: branch-validation
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH for Bitbucket
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BITBUCKET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts

      - name: Install Fastlane
        run: gem install fastlane

      - name: Deploy to TestFlight
        run: fastlane beta
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
