---
name: Alfie CI/CD

on:
  push:
    branches:
      - main
      - release/**
  workflow_dispatch:

env:
  IOS_DESTINATION: "platform=iOS Simulator,name=iPhone 14"
  DEVELOPER_DIR: "/Applications/Xcode_16.app/Contents/Developer"

jobs:
  branch-validation:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run Code Linting
        run: swiftlint

      - name: Run Static Code Analysis
        run: |
         xcodebuild analyze \
           -scheme Alfie \
           -destination "${{ env.IOS_DESTINATION }}"

      - name: Run Unit Tests
        run: |
         xcodebuild test \
           -scheme Alfie \
           -destination "${{ env.IOS_DESTINATION }}"

  testflight-build:
    needs: branch-validation
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH for Bitbucket
        run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.BITBUCKET_SSH_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts

      - name: Install Fastlane
        run: |
          brew install fastlane
          gem install bundler
          bundle install --path vendor/bundle

      - name: Run Fastlane Match
        run: |
          bundle exec fastlane match appstore
        env:
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BRANCH: ${{ secrets.MATCH_GIT_BRANCH }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_API_KEY_FILEPATH: ${{ secrets.API_KEY_PATH }}

      - name: Increment Build Number
        run: agvtool next-version -all

      - name: Configure Git User
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Commit and Push Build Number
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git add .
          git commit -m "Increment build to $(agvtool what-version -terse)"
          git push origin HEAD

      - name: Build and Archive
        run: |
          xcodebuild clean archive \
           -scheme Alfie \
           -archivePath $PWD/build/App.xcarchive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive \
          -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build

      - name: Deploy to TestFlight
        run: |
         fastlane pilot upload -i $PWD/build/App.ipa
