---
name: Alfie CI/CD

on:
  push:
    branches: ['main', 'release/**', 'ALFMOB-33_Implemented_CI_CD']
  
  pull_request:
    branches: ['main', 'release/**', 'ALFMOB-33_Implemented_CI_CD']

  workflow_dispatch:

env:
  DEVELOPER_DIR: "/Applications/Xcode_16.app/Contents/Developer"

jobs:
  branch-validation:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Fastlane
        run: gem install fastlane

      - name: Validate Tests
        run: fastlane validate_tests
        env:
          IOS_DESTINATION: ${{ env.IOS_DESTINATION }}
      
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Test-Results
          path: |
              ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
          retention-days: 7

  testflight-build:
    needs: branch-validation
    runs-on: macos-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH for Bitbucket
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BITBUCKET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts

      - name: Install Fastlane
        run: gem install fastlane

      - name: Deploy to TestFlight
        run: fastlane beta
        env:
          APPSTORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
          APPSTORE_CONNECT_KEY_CONTENT_BASE64: ${{ secrets.APPSTORE_CONNECT_KEY_CONTENT_BASE64 }}
          APPSTORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_CONNECT_KEY_ID }}
          APPSTORE_CONNECT_TEAM_ID: ${{ secrets.APPSTORE_CONNECT_TEAM_ID }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          ITUNESCONNECT_TEAM_ID: ${{ secrets.ITUNESCONNECT_TEAM_ID }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
