included:
  - Alfie
  - AlfieKit
excluded:
  - .build
  - AlfieKit/Sources/SharedUI/Localization/L10n+Generated.swift
  - scripts
  - DerivedData
  - AlfieKit/.build
  - AlfieKit/.swiftpm
  - AlfieKit/Package.swift
  - AlfieKit/Sources/BFFGraph
  - AlfieKit/Sources/Mocks
  - AlfieKit/Tests
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - all
disabled_rules:
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - anyobject_protocol
  - closure_body_length
  - conditional_returns_on_newline
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - file_types_order
  - file_name
  - function_default_parameter_at_end
  - inert_defer
  - missing_docs
  - nesting
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - prefer_nimble
  - prefer_self_in_static_references
  - prefixed_toplevel_constant
  - required_deinit
  - type_contents_order
  - unused_capture_list
  - discouraged_optional_boolean
  - accessibility_label_for_image
  - lower_acl_than_parent
  - fatal_error
  - unavailable_function
  - number_separator
  - cyclomatic_complexity
  - nslocalizedstring_require_bundle
  - pattern_matching_keywords
  - extension_access_modifier
  - sorted_enum_cases
  - redundant_self_in_closure
  - superfluous_else
attributes:
  attributes_with_arguments_always_on_line_above: false
identifier_name:
  min_length: 2
  validates_start_with_lowercase: warning
large_tuple: 3
function_body_length: 200
type_body_length: 400
trailing_comma:
  mandatory_comma: true
line_length:
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_function_declarations: true
  ignores_urls: true
custom_rules:
  fatal_error:
    name: Fatal Error
    excluded: "Tests/*"
    message: Prefer using `queuedFatalError` over `fatalError` to avoid leaking compiler host machine paths.
    regex: \bfatalError\b
    match_kinds:
      - identifier
  debug_Mocks:
    name: Debug Mock
    excluded: "Tests/*"
    message: Preview should only work on Debug
    regex: '^\}\n*\#Preview$'
    severity: error
unused_import:
  always_keep_imports:
    - SwiftSyntaxBuilder
